### PR TITLE
run post release after github-release

### PR DESCRIPTION
**Pull request by sdelamo**
post release: https://github.com/micronaut-projects/github-actions/blob/master/post-release/entrypoint.sh

I hope this fixes: 

Close: #389

### CODE REVIEW

**Comment by sdelamo** [comment]
I created a PR to try this with a security release first https://github.com/micronaut-projects/micronaut-security/pull/1410

**Review by alvarosanchez — APPROVED** [review]

**Comment by sdelamo** [comment]
I think we should do this change but it still does not fixes the issue of the tagged code having a snapshot version: 

https://github.com/micronaut-projects/micronaut-security/blob/v4.0.3/gradle.properties#L1

My guess this is happening after we added this code which helped us fix the double release issue: 

https://github.com/micronaut-projects/micronaut-starter/commit/c00ad2515c014be6dc0cebbe2d6ef7b2ce93cc66

@timyates can you check our release process once you are back?

**Comment by timyates** [comment]
I believe the issue is that when we release:

1. Something (github?) tags the current commit with `vX.X.X`
2. We then update the version in gradle properties, update the tag and push
3. [Updating the tag fails](https://github.com/micronaut-projects/micronaut-security/actions/runs/5763379773/job/15625052171#step:9:212) as it already exists on the remote

```
Pushing release version and recreating v4.0.3 tag
[master 7c6a902ad] [skip ***] Release v4.0.3
 1 file changed, 1 insertion(+), 1 deletion(-)
remote: Bypassed rule violations for refs/heads/master:        
remote: 
remote: - 2 of 2 required status checks are expected.        
remote: 
remote: 
remote: GitHub found 1 vulnerability on micronaut-projects/micronaut-security's default branch (1 high). To find out more, visit:        
remote:      https://github.com/micronaut-projects/micronaut-security/security/dependabot/1        
remote: 
To https://github.com/micronaut-projects/micronaut-security
   76d93963e..7c6a902ad  master -> master
Updated tag 'v4.0.3' (was 76d93963e)
To https://github.com/micronaut-projects/micronaut-security
 ! [rejected]            v4.0.3 -> v4.0.3 (already exists)
error: failed to push some refs to 'https://github.com/micronaut-projects/micronaut-security'
hint: Updates were rejected because the tag already exists in the remote.
```

So we end up with the tag pointing to the commit prior to the release

image

I'll keep looking

**Comment by timyates** [comment]
I think what we're seeing is caused by https://github.com/micronaut-projects/github-actions/pull/33

Not sure why that was done, there's no context in the PR

**Comment by timyates** [comment]
Apparently that was done as;

> that helped to fix the issues with the release getting duplicated (one published one snapshot)

**Comment by timyates** [comment]
I am not sure what the original issue was (as I was out), I'll discuss with @sdelamo when he is back in

**Comment by alvarosanchez** [comment]
https://github.com/micronaut-projects/github-actions/pull/33 was an attempt to avoid the problem we had with 80% of our releases that would stay "untagged" and back to draft after the release is complete.

Feel free to revert it.

**Comment by timyates** [comment]
@alvarosanchez instead of reverting, I added a git command to just force-push the updated tag https://github.com/micronaut-projects/github-actions/pull/35

**Comment by timyates** [comment]
If we go with https://github.com/micronaut-projects/github-actions/pull/35, I'm not sure this PR is required 🤔

**Comment by sdelamo** [comment]
It seems [gitHub-actions#35 ](https://github.com/micronaut-projects/github-actions/pull/35) is enough. At least, in the servlet 4.0.2 release I saw no duplication of the [release and the `projectVersion` was not snapshot](https://github.com/micronaut-projects/micronaut-servlet/blob/v4.0.2/gradle.properties#L1).

**Pull request closed without merging**
