### PR TITLE
Globally enable GraalVM quick build mode for tests

### PR DESCRIPTION
**Pull request by alvarosanchez**

### CODE REVIEW

**Review by melix — APPROVED** [review]
I suspect we can miss some errors by doing this, but it's probably a safe tradeoff. @gradinac what do you think?

**Comment by gradinac** [comment]
I am not as familiar with the quickbuild mode, but at it's core, it disables some native-image compilation phases to reduce the `compile` step duration - the resulting image will not be exactly the same as what users will run
Personally, if possible I would run tests without the `quickbuild` mode as that's probably the closest to what users will run (atleast right now) unless the CI times are reduced substantially with it - but I think turning it on should be safe (although it should probably be monitored for some time once it is)

**Comment by alvarosanchez** [comment]
I don't think we are any safer or test any better with non-quick mode. In most of the cases, we only test that the native image builds. There are also a few cases where we actually run it, but for that, we don't need a production-grade binary, do we?

@micronaut-projects/core-developers thoughts?

**Comment by yawkat** [comment]
what issues could this miss? most of the bugs we see with graal are reflection- or classpath-related, and those should still show up, but if there's the possibility of missing other more rare bugs, maybe we can keep running normal mode on CI?

**Comment by sdelamo** [comment]
This seems to be causing issues https://github.com/micronaut-projects/micronaut-sql/runs/7538645832?check_suite_focus=true

**Comment by melix** [comment]
For reference: https://github.com/graalvm/native-build-tools/pull/278

**Comment by graemerocher** [comment]
This change needs to be reverted until that is fixed

**Comment by alvarosanchez** [comment]
https://github.com/micronaut-projects/micronaut-project-template/pull/251

**Pull request merged**
