### PR TITLE
sync only on the weekends not on push to master

### PR DESCRIPTION
**Pull request by sdelamo**
The goal of this change is to reduce the number of PRs.

### CODE REVIEW

**Comment by alvarosanchez** [comment]
Can we sync during the night (CET timezone) instead?

**Comment by sdelamo** [comment]
> Can we sync during the night (CET timezone) instead?

I think this is 

> Can we sync during the night (CET timezone) instead?

[It uses UTC](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule).  

5 am UTC is 6am CET. that is fine right? Or do you want me to set it to 4am UTC?

**Comment by alvarosanchez** [comment]
I mean every night, not only on saturdays

**Comment by sdelamo** [comment]
@alvarosanchez I changed to every day at 5am

**Comment by sdelamo** [comment]
ping @alvarosanchez

**Pull request merged**
