### PR TITLE
fix(ci): revert github release upload assets and use gh cli

### PR DESCRIPTION
**Pull request by behnazh-w**
As noted by @alvarosanchez in [this issue](https://github.com/micronaut-projects/micronaut-project-template/issues/351):
>Usually when a GitHub release is moved back to draft is because it has been edited. Our custom GitHub actions have always taken care of this by re-closing the releases, but perhaps something that was there and now is missing is preventing this to work.

[The recent change ](https://github.com/micronaut-projects/micronaut-project-template/pull/346)that used `softprops/action-gh-release` to upload the release assets might have caused this change that prevents custom GitHub actions to re-close the release. This PR removes `softprops/action-gh-release`. 

To solve the race condition issue pointed out in [this PR](https://github.com/micronaut-projects/micronaut-project-template/pull/346), I have changed `github_release` job to depend on `provenance` instead of the `release` job to give GitHub APIs more time to find an existing release.

### CODE REVIEW

**Comment by alvarosanchez** [comment]
It could be because of this, or it could be because of https://github.com/micronaut-projects/github-actions/pull/23

**Comment by sdelamo** [comment]
The issue #351  is still happening.  I just had this problem with Micronaut Liquibase.

**Comment by alvarosanchez** [comment]
It's worth trying this

**Comment by sdelamo** [comment]
@alvarosanchez we can close this?

**Pull request closed without merging**
