### PR TITLE
Adds Link for CLA aggreement

### PR DESCRIPTION
**Pull request by ashishkujoy**

### CODE REVIEW

**Comment by graemerocher** [comment]
Does you `push` with an empty string mean the action it only runs when the repo is created?

**Comment by ashishkujoy** [comment]
> Does you `push` with an empty string mean t

Indirectly Yes, as soon as a new repo is created with this template the action will get trigger, and this action itself will update the CLA link and then delete this action file, so effectively this action will run only once.

**Review by ilopmar — APPROVED** [review]

**Comment by ashishkujoy** [comment]
@ilopmar In case this pull request is good to merge, can u please add `hacktoberfest-accepted` label to it.

**Comment by ilopmar** [comment]
@ashishkujoy sorry for the delay. We've been discussing this internally and we've decided to create the label for all of our repos.

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
