### PR TITLE
Explain how to deal with the 2 types of dependency upgrade PRs

### PR DESCRIPTION
**Pull request by alvarosanchez**

### CODE REVIEW

**Review by ilopmar — APPROVED** [review]

**Comment by ilopmar** [comment]
@alvarosanchez Hold on, I'm going to push a minor fix in this file regarding new snapshots

**Comment by ilopmar** [comment]
done

**Comment by alvarosanchez** [comment]
Good catch, thanks.

I'm leaving this open for today anyway, just in case I see more things to add.

**Comment by ilopmar** [comment]
Good idea :)

**Pull request merged**
